### ISSUE TITLE
Using a CSS3 background gradient

### ISSUE THREAD

**Issue by herrjosua** [VincentGarreau/particles.js#161]
I'm trying to use a CSS3 background gradient but when I do, all I get is a white background. This is the CSS I am using on the `body` below the current `background-color` attribute:

`background: linear-gradient(135deg, #ee383d  0%, #ffcc5d  100%);`

**Comment by Ediolot** [comment]
This is working for me in the Codepen example in Chrome.
```css
#particles-js {
    position: absolute;
    width: 100%;
    height: 100%;
    background: linear-gradient(135deg, #ee383d 0%, #ffcc5d 100%);
}
````

**Comment by DarkIBL** [comment]
Do like @Ediolot, but change the background for body to transparent.
```css
body {
     background-color: transparent;
}
```
